DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS haibenrecord;
CREATE TABLE users(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    username VARCHAR(20) NOT NULL UNIQUE
);
CREATE TABLE haibenrecord(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    userid INTEGER NOT NULL,
    record VARCHAR(20) NOT NULL,
    FOREIGN KEY (userid) REFERENCES users(id)
);